services:
    - docker

language: shell

addons:
    ssh_known_hosts: loopylab.de

script:
    - docker run --rm --volume=$(pwd):/srv/jekyll jekyll/jekyll /bin/bash -c "chmod a+wx . && jekyll build -V"

before_deploy:
    - eval "$(ssh-agent -s)"
    - openssl aes-256-cbc -K $encrypted_496074b8526a_key -iv $encrypted_496074b8526a_iv -in .travis/travis_uploader_key.enc -out /tmp/travis_uploader_key -d
    - chmod 600 /tmp/travis_uploader_key
    - ssh-add /tmp/travis_uploader_key

deploy:
    skip_cleanup: true
    provider: script
    script: sftp uploader@dirkheinke.de:content/loopylab.de <<< $'put -R _site/*'
    on:
        branch: master
