sudo: require

services:
    - docker

language: bash

script:
    -  docker run --rm --volume=$(pwd):/srv/jekyll jekyll/jekyll jekyll build -V

before_deploy:
    - eval "$(ssh-agent -s)"
    - echo ${SSH_KEY} > /tmp/ssh_key
    - chmod 600 /tmp/ssh_key
    - ssh-add /tmp/ssh_key

deploy:
    skip_cleanup: true
    provider: script
    script: _deploy.sh
    on:
        branch: master
