url: "http://loopylab.de"
paginate: 5
kramdown:
  input: GFM
defaults:
  -
    scope:
        path: "" # an empty string here means all files in the project
    values:
        layout: "default"
plugins:
  - jekyll-sitemap
  - jekyll-paginate